CREATE TABLE job_posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    location    VARCHAR(255)                            NOT NULL,
    salary      DOUBLE PRECISION                        NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_job_posts PRIMARY KEY (id)
);

CREATE TABLE todos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    completed   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);


CREATE TABLE users_type
(
    user_type_id   SERIAL PRIMARY KEY,
    user_type_name VARCHAR(255)
);

INSERT INTO users_type
VALUES (1, 'Recruiter'),
       (2, 'Job Seeker');

CREATE TABLE users
(
    user_id           SERIAL PRIMARY KEY,
    email             VARCHAR(255) UNIQUE,
    is_active         BOOLEAN      DEFAULT NULL,
    password          VARCHAR(255) DEFAULT NULL,
    registration_date TIMESTAMP    DEFAULT NULL,
    user_type_id      INT          DEFAULT NULL,
    CONSTRAINT fk_user_type FOREIGN KEY (user_type_id) REFERENCES users_type (user_type_id)
);


CREATE TABLE candidate_profile
(
    user_account_id    INT NOT NULL,
    city               VARCHAR(255) DEFAULT NULL,
    country            VARCHAR(255) DEFAULT NULL,
    employment_type    VARCHAR(255) DEFAULT NULL,
    first_name         VARCHAR(255) DEFAULT NULL,
    last_name          VARCHAR(255) DEFAULT NULL,
    profile_photo      VARCHAR(255) DEFAULT NULL,
    resume             VARCHAR(255) DEFAULT NULL,
    state              VARCHAR(255) DEFAULT NULL,
    work_authorization VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (user_account_id),
    CONSTRAINT fk_user_account FOREIGN KEY (user_account_id) REFERENCES users (user_id)
);



CREATE TABLE skills
(
    id                  SERIAL PRIMARY KEY,
    experience_level    VARCHAR(255) DEFAULT NULL,
    name                VARCHAR(255) DEFAULT NULL,
    years_of_experience VARCHAR(255) DEFAULT NULL,
    candidate_profile   INT          DEFAULT NULL,
    CONSTRAINT fks_job_seeker_profile FOREIGN KEY (candidate_profile) REFERENCES candidate_profile (user_account_id)
);

CREATE TABLE job_location
(
    id      SERIAL PRIMARY KEY,
    city    VARCHAR(255) DEFAULT NULL,
    country VARCHAR(255) DEFAULT NULL,
    state   VARCHAR(255) DEFAULT NULL
);

CREATE TABLE recruiter_profile
(
    user_account_id INT NOT NULL,
    city            VARCHAR(255) DEFAULT NULL,
    company         VARCHAR(255) DEFAULT NULL,
    country         VARCHAR(255) DEFAULT NULL,
    first_name      VARCHAR(255) DEFAULT NULL,
    last_name       VARCHAR(255) DEFAULT NULL,
    profile_photo   VARCHAR(64)  DEFAULT NULL,
    state           VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (user_account_id),
    CONSTRAINT fk_user_account FOREIGN KEY (user_account_id) REFERENCES users (user_id)
);