CREATE TABLE job_posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    location    VARCHAR(255)                            NOT NULL,
    salary      DOUBLE PRECISION                        NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_job_posts PRIMARY KEY (id)
);

CREATE TABLE todos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    completed   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);