services:
  postgres:
    image: postgres:15
    container_name: postgres-truckprojobs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: truckprojobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - truckprojobs-network

volumes:
  postgres_data:

networks:
  truckprojobs-network:
    driver: bridge